services:
  claude-hukuk-asistani:
    # Bu satır, konteynerin adını her zaman sabit tutar.
    container_name: ai-hukuk-asistani-dev
    build: .
    ports:
      - "8501:8501"
    working_dir: /app
    volumes:
      - ./:/app
    command: bash
    stdin_open: true
    tty: true